### PR TITLE
Fix compilation issue for x64 hardware

### PR DESCRIPTION
**Pull request by abidon**
As explained in [Float16](https://developer.apple.com/documentation/swift/float16) documentation, the type is only available when targetting Apple Silicon hardware.

The `@available` directive is not enough to ignore this function on x64 hardware, causing compilation errors.

This PR comes with [a twin](https://github.com/QuickBirdEng/crc-swift/pull/2) on the crc-swift repository.

### CODE REVIEW

**Comment by abidon** [comment]
I leave this PR as a draft until the CRC pull request gets updated and a release is made for CRC (0.1.1 maybe?).

Once done, I'll update the dependency in the `Package.swift` file in this PR and it will be ready for merge.

**Comment by pauljohanneskraft** [comment]
@abidon Thank you for the fix and sorry for the delayed response. The release has been created: https://github.com/QuickBirdEng/crc-swift/releases/tag/0.1.1. Alternatively, we could also merge this PR now and handle the version restriction in an upcoming PR.

**Comment by abidon** [comment]
@pauljohanneskraft No worries 😉 It's all good, I pushed an additional commit with the bumped version of `crc-swift`

**Comment by pauljohanneskraft** [comment]
Perfect - thank you  very much!

**Review by pauljohanneskraft — APPROVED** [review]

**Pull request merged**
